---
- name: Register system with Red Hat Subscription Manager
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool_id }}"

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest

- name: Use IPA role to install
  ansible.builtin.include_role:
    name: freeipa.ansible_freeipa.ipaserver
